### ISSUE TITLE
Double click not working on mozzila

### ISSUE THREAD

**Issue by dnanusevski** [mazong1123/fabric.ext#5]
How to make double click working on mozzila ?

**Comment by dnanusevski** [comment]
canvas.getPointer(event.e); is pointed as a mistake

**Comment by dnanusevski** [comment]
Sory ! Double click is working but getting cordinates is not

**Comment by mazong1123** [comment]
@dnanusevski could you please file another issue for the cordinates error? I'd like to reproduce this bug in molliza, thanks.
